[package]
name = "pyo3_counter_example"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.21.2", features = ["extension-module"] }

[lib]
crate-type = ["cdylib"]

[profile.release]
strip = true
